//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMF.Client
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailMessage", Namespace="http://www.marykay.com/")]
    public partial class EmailMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentRootField;
        
        private string ContentDomainField;
        
        private string ContentIDField;
        
        private string SenderField;
        
        private string SubjectField;
        
        private GMF.Client.ArrayOfString RecipientsField;
        
        private GMF.Client.EmailAttribute[] ValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentRoot
        {
            get
            {
                return this.ContentRootField;
            }
            set
            {
                this.ContentRootField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ContentDomain
        {
            get
            {
                return this.ContentDomainField;
            }
            set
            {
                this.ContentDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContentID
        {
            get
            {
                return this.ContentIDField;
            }
            set
            {
                this.ContentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public GMF.Client.ArrayOfString Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public GMF.Client.EmailAttribute[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.marykay.com/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAttribute", Namespace="http://www.marykay.com/")]
    public partial class EmailAttribute : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRecipient", Namespace="http://www.marykay.com/")]
    public partial class EmailRecipient : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RecipientField;
        
        private GMF.Client.EmailAttribute[] AttributesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GMF.Client.EmailAttribute[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://www.marykay.com/")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentRootField;
        
        private string ContentDomainField;
        
        private string ContentIDField;
        
        private string SenderField;
        
        private string SubjectField;
        
        private GMF.Client.MessageRecipient[] RecipientsField;
        
        private GMF.Client.MessageValue[] ValuesField;
        
        private GMF.Client.MessageAttribute[] AttributesField;
        
        private short StatusTypeIDField;
        
        private short RetentionTypeIDField;
        
        private string RenderingTypeField;
        
        private short SendTypeIDField;
        
        private System.DateTime SendDateField;
        
        private short RetentionOffsetField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentRoot
        {
            get
            {
                return this.ContentRootField;
            }
            set
            {
                this.ContentRootField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ContentDomain
        {
            get
            {
                return this.ContentDomainField;
            }
            set
            {
                this.ContentDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContentID
        {
            get
            {
                return this.ContentIDField;
            }
            set
            {
                this.ContentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public GMF.Client.MessageRecipient[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public GMF.Client.MessageValue[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public GMF.Client.MessageAttribute[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public short StatusTypeID
        {
            get
            {
                return this.StatusTypeIDField;
            }
            set
            {
                this.StatusTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public short RetentionTypeID
        {
            get
            {
                return this.RetentionTypeIDField;
            }
            set
            {
                this.RetentionTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RenderingType
        {
            get
            {
                return this.RenderingTypeField;
            }
            set
            {
                this.RenderingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public short SendTypeID
        {
            get
            {
                return this.SendTypeIDField;
            }
            set
            {
                this.SendTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public short RetentionOffset
        {
            get
            {
                return this.RetentionOffsetField;
            }
            set
            {
                this.RetentionOffsetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRecipient", Namespace="http://www.marykay.com/")]
    public partial class MessageRecipient : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RecipientField;
        
        private GMF.Client.MessageAttribute[] AttributesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GMF.Client.MessageAttribute[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageValue", Namespace="http://www.marykay.com/")]
    public partial class MessageValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string ValueField;
        
        private string TypeField;
        
        private GMF.Client.MessageAttribute[] AttributesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GMF.Client.MessageAttribute[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageAttribute", Namespace="http://www.marykay.com/")]
    public partial class MessageAttribute : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.marykay.com/", ConfigurationName="GMF.Contracts.WSSendMailSoap")]
    public interface ISendMailService
    {
        
        // CODEGEN: Generating message contract since element name senderEmail from namespace http://www.marykay.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.marykay.com/SendSimpleEmail")]
        GMF.Client.SendSimpleEmailResponse SendSimpleEmail(GMF.Client.SendSimpleEmailRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://www.marykay.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.marykay.com/SendTemplatedEmail")]
        GMF.Client.SendTemplatedEmailResponse SendTemplatedEmail(GMF.Client.SendTemplatedEmailRequest request);
        
        // CODEGEN: Generating message contract since element name contentDomain from namespace http://www.marykay.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.marykay.com/SendPredefinedEmail")]
        GMF.Client.SendPredefinedEmailResponse SendPredefinedEmail(GMF.Client.SendPredefinedEmailRequest request);
        
        // CODEGEN: Generating message contract since element name message from namespace http://www.marykay.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.marykay.com/SendMessage")]
        GMF.Client.SendMessageResponse SendMessage(GMF.Client.SendMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleEmail", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendSimpleEmailRequestBody Body;
        
        public SendSimpleEmailRequest()
        {
        }
        
        public SendSimpleEmailRequest(GMF.Client.SendSimpleEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marykay.com/")]
    public partial class SendSimpleEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipientEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string recipientContactID;
        
        public SendSimpleEmailRequestBody()
        {
        }
        
        public SendSimpleEmailRequestBody(string senderEmail, string recipientEmail, string subject, string content, string domain, string recipientContactID)
        {
            this.senderEmail = senderEmail;
            this.recipientEmail = recipientEmail;
            this.subject = subject;
            this.content = content;
            this.domain = domain;
            this.recipientContactID = recipientContactID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleEmailResponse", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendSimpleEmailResponseBody Body;
        
        public SendSimpleEmailResponse()
        {
        }
        
        public SendSimpleEmailResponse(GMF.Client.SendSimpleEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendSimpleEmailResponseBody
    {
        
        public SendSimpleEmailResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplatedEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplatedEmail", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendTemplatedEmailRequestBody Body;
        
        public SendTemplatedEmailRequest()
        {
        }
        
        public SendTemplatedEmailRequest(GMF.Client.SendTemplatedEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marykay.com/")]
    public partial class SendTemplatedEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GMF.Client.EmailMessage email;
        
        public SendTemplatedEmailRequestBody()
        {
        }
        
        public SendTemplatedEmailRequestBody(GMF.Client.EmailMessage email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplatedEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplatedEmailResponse", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendTemplatedEmailResponseBody Body;
        
        public SendTemplatedEmailResponse()
        {
        }
        
        public SendTemplatedEmailResponse(GMF.Client.SendTemplatedEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendTemplatedEmailResponseBody
    {
        
        public SendTemplatedEmailResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPredefinedEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPredefinedEmail", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendPredefinedEmailRequestBody Body;
        
        public SendPredefinedEmailRequest()
        {
        }
        
        public SendPredefinedEmailRequest(GMF.Client.SendPredefinedEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marykay.com/")]
    public partial class SendPredefinedEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentDomain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public GMF.Client.EmailRecipient[] recipients;
        
        public SendPredefinedEmailRequestBody()
        {
        }
        
        public SendPredefinedEmailRequestBody(string contentDomain, string contentID, string subject, string sender, GMF.Client.EmailRecipient[] recipients)
        {
            this.contentDomain = contentDomain;
            this.contentID = contentID;
            this.subject = subject;
            this.sender = sender;
            this.recipients = recipients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPredefinedEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPredefinedEmailResponse", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendPredefinedEmailResponseBody Body;
        
        public SendPredefinedEmailResponse()
        {
        }
        
        public SendPredefinedEmailResponse(GMF.Client.SendPredefinedEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendPredefinedEmailResponseBody
    {
        
        public SendPredefinedEmailResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendMessageRequestBody Body;
        
        public SendMessageRequest()
        {
        }
        
        public SendMessageRequest(GMF.Client.SendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marykay.com/")]
    public partial class SendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GMF.Client.Message message;
        
        public SendMessageRequestBody()
        {
        }
        
        public SendMessageRequestBody(GMF.Client.Message message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.marykay.com/", Order=0)]
        public GMF.Client.SendMessageResponseBody Body;
        
        public SendMessageResponse()
        {
        }
        
        public SendMessageResponse(GMF.Client.SendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marykay.com/")]
    public partial class SendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendMessageResult;
        
        public SendMessageResponseBody()
        {
        }
        
        public SendMessageResponseBody(long SendMessageResult)
        {
            this.SendMessageResult = SendMessageResult;
        }
    }
}
