//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myCustomers.Services.NetCC
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICCProcessing")]
    public interface ICCProcessing
    {
        // CODEGEN: Generating message contract since the wrapper name (EncryptCCNumberUnAssociated) of message EncryptCCNumberUnAssociated does not match the default value (EncryptCCNumber)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptCCNumberUnAssociated")]
        EncryptCCNumberUnAssociated1 EncryptCCNumber(EncryptCCNumberUnAssociated request);
        
        // CODEGEN: Generating message contract since the wrapper name (EncryptCCNumber) of message EncryptCCNumberRequest does not match the default value (EncryptCCNumber1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptCCNumber")]
        EncryptCCNumberResponse EncryptCCNumber1(EncryptCCNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RefundProPayPayment")]
        int RefundProPayPayment(long amount, long accountNum, long transNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeProPayPayment")]
        AuthorizeProPayPaymentResponse AuthorizeProPayPayment(AuthorizeProPayPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeProPayPayment_Canada")]
        AuthorizeProPayPayment_CanadaResponse AuthorizeProPayPayment_Canada(AuthorizeProPayPayment_CanadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeProPayPaymentForMerrittInsurance")]
        AuthorizeProPayPaymentForMerrittInsuranceResponse AuthorizeProPayPaymentForMerrittInsurance(AuthorizeProPayPaymentForMerrittInsuranceRequest request);
        
        // CODEGEN: Generating message contract since element name GetProPayPaymentStatusResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProPayPaymentStatus")]
        GetProPayPaymentStatusResponse GetProPayPaymentStatus(GetProPayPaymentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeProPayPaymentForMerrittInsuranceTest")]
        AuthorizeProPayPaymentForMerrittInsuranceTestResponse AuthorizeProPayPaymentForMerrittInsuranceTest(AuthorizeProPayPaymentForMerrittInsuranceTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeProPayTimedPull")]
        int AuthorizeProPayTimedPull(long accountnumber, long amount, long transactionnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreAuthAndSaveCardSpecifyingCCPaymentID")]
        GetPreAuthAndSaveCardSpecifyingCCPaymentID1 GetPreAuth(GetPreAuthAndSaveCardSpecifyingCCPaymentID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreAuthAndSaveCard")]
        GetPreAuthAndSaveCard1 GetPreAuth1(GetPreAuthAndSaveCard request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreAuthUsingToken")]
        GetPreAuthUsingToken1 GetPreAuth2(GetPreAuthUsingToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPreAuth")]
        GetPreAuthResponse GetPreAuth3(GetPreAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoPostAuth")]
        DoPostAuthResponse DoPostAuth(DoPostAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVoid")]
        IssueVoidResponse IssueVoid(IssueVoidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueCredit")]
        IssueCreditResponse IssueCredit(IssueCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SettleTransactions")]
        SettleTransactionsResponse SettleTransactions(SettleTransactionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptCCNumberUnAssociated", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptCCNumberUnAssociated
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ccnumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime expirationdate;
        
        public EncryptCCNumberUnAssociated()
        {
        }
        
        public EncryptCCNumberUnAssociated(string ccnumber, System.DateTime expirationdate)
        {
            this.ccnumber = ccnumber;
            this.expirationdate = expirationdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptCCNumberUnAssociatedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptCCNumberUnAssociated1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid EncryptCCNumberUnAssociatedResult;
        
        public EncryptCCNumberUnAssociated1()
        {
        }
        
        public EncryptCCNumberUnAssociated1(System.Guid EncryptCCNumberUnAssociatedResult)
        {
            this.EncryptCCNumberUnAssociatedResult = EncryptCCNumberUnAssociatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptCCNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptCCNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long contactid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ccnumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime expirationdate;
        
        public EncryptCCNumberRequest()
        {
        }
        
        public EncryptCCNumberRequest(long contactid, string ccnumber, System.DateTime expirationdate)
        {
            this.contactid = contactid;
            this.ccnumber = ccnumber;
            this.expirationdate = expirationdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptCCNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptCCNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid EncryptCCNumberResult;
        
        public EncryptCCNumberResponse()
        {
        }
        
        public EncryptCCNumberResponse(System.Guid EncryptCCNumberResult)
        {
            this.EncryptCCNumberResult = EncryptCCNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPayment", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentRequestBody Body;
        
        public AuthorizeProPayPaymentRequest()
        {
        }
        
        public AuthorizeProPayPaymentRequest(AuthorizeProPayPaymentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long PaymentAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ZipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Guid CCToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CCExpirationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InvoiceNumber;
        
        public AuthorizeProPayPaymentRequestBody()
        {
        }
        
        public AuthorizeProPayPaymentRequestBody(long PaymentAmount, string Address, string ZipCode, long AccountNumber, System.Guid CCToken, string CCExpirationDate, string InvoiceNumber)
        {
            this.PaymentAmount = PaymentAmount;
            this.Address = Address;
            this.ZipCode = ZipCode;
            this.AccountNumber = AccountNumber;
            this.CCToken = CCToken;
            this.CCExpirationDate = CCExpirationDate;
            this.InvoiceNumber = InvoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentResponseBody Body;
        
        public AuthorizeProPayPaymentResponse()
        {
        }
        
        public AuthorizeProPayPaymentResponse(AuthorizeProPayPaymentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long TransactionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AVSResponseCode;
        
        public AuthorizeProPayPaymentResponseBody()
        {
        }
        
        public AuthorizeProPayPaymentResponseBody(string AuthCode, long TransactionNumber, int TransactionStatus, string AVSResponseCode)
        {
            this.AuthCode = AuthCode;
            this.TransactionNumber = TransactionNumber;
            this.TransactionStatus = TransactionStatus;
            this.AVSResponseCode = AVSResponseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPayment_CanadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPayment_Canada", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPayment_CanadaRequestBody Body;
        
        public AuthorizeProPayPayment_CanadaRequest()
        {
        }
        
        public AuthorizeProPayPayment_CanadaRequest(AuthorizeProPayPayment_CanadaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPayment_CanadaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long PaymentAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ZipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Guid CCToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CCExpirationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InvoiceNumber;
        
        public AuthorizeProPayPayment_CanadaRequestBody()
        {
        }
        
        public AuthorizeProPayPayment_CanadaRequestBody(long PaymentAmount, string Address, string ZipCode, long AccountNumber, System.Guid CCToken, string CCExpirationDate, string InvoiceNumber)
        {
            this.PaymentAmount = PaymentAmount;
            this.Address = Address;
            this.ZipCode = ZipCode;
            this.AccountNumber = AccountNumber;
            this.CCToken = CCToken;
            this.CCExpirationDate = CCExpirationDate;
            this.InvoiceNumber = InvoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPayment_CanadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPayment_CanadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPayment_CanadaResponseBody Body;
        
        public AuthorizeProPayPayment_CanadaResponse()
        {
        }
        
        public AuthorizeProPayPayment_CanadaResponse(AuthorizeProPayPayment_CanadaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPayment_CanadaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long TransactionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AVSResponseCode;
        
        public AuthorizeProPayPayment_CanadaResponseBody()
        {
        }
        
        public AuthorizeProPayPayment_CanadaResponseBody(string AuthCode, long TransactionNumber, int TransactionStatus, string AVSResponseCode)
        {
            this.AuthCode = AuthCode;
            this.TransactionNumber = TransactionNumber;
            this.TransactionStatus = TransactionStatus;
            this.AVSResponseCode = AVSResponseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPaymentForMerrittInsurance", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentForMerrittInsuranceRequestBody Body;
        
        public AuthorizeProPayPaymentForMerrittInsuranceRequest()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceRequest(AuthorizeProPayPaymentForMerrittInsuranceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long PaymentAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ZipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CCNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CCExpirationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InvoiceNumber;
        
        public AuthorizeProPayPaymentForMerrittInsuranceRequestBody()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceRequestBody(long PaymentAmount, string Address, string ZipCode, long AccountNumber, string CCNumber, string CCExpirationDate, string InvoiceNumber)
        {
            this.PaymentAmount = PaymentAmount;
            this.Address = Address;
            this.ZipCode = ZipCode;
            this.AccountNumber = AccountNumber;
            this.CCNumber = CCNumber;
            this.CCExpirationDate = CCExpirationDate;
            this.InvoiceNumber = InvoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPaymentForMerrittInsuranceResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentForMerrittInsuranceResponseBody Body;
        
        public AuthorizeProPayPaymentForMerrittInsuranceResponse()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceResponse(AuthorizeProPayPaymentForMerrittInsuranceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long TransactionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AVSResponseCode;
        
        public AuthorizeProPayPaymentForMerrittInsuranceResponseBody()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceResponseBody(string AuthCode, long TransactionNumber, int TransactionStatus, string AVSResponseCode)
        {
            this.AuthCode = AuthCode;
            this.TransactionNumber = TransactionNumber;
            this.TransactionStatus = TransactionStatus;
            this.AVSResponseCode = AVSResponseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProPayPaymentStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProPayPaymentStatus", Namespace="http://tempuri.org/", Order=0)]
        public GetProPayPaymentStatusRequestBody Body;
        
        public GetProPayPaymentStatusRequest()
        {
        }
        
        public GetProPayPaymentStatusRequest(GetProPayPaymentStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProPayPaymentStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long TransactionNumber;
        
        public GetProPayPaymentStatusRequestBody()
        {
        }
        
        public GetProPayPaymentStatusRequestBody(long AccountNumber, long TransactionNumber)
        {
            this.AccountNumber = AccountNumber;
            this.TransactionNumber = TransactionNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProPayPaymentStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProPayPaymentStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetProPayPaymentStatusResponseBody Body;
        
        public GetProPayPaymentStatusResponse()
        {
        }
        
        public GetProPayPaymentStatusResponse(GetProPayPaymentStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProPayPaymentStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProPayPaymentStatusResult;
        
        public GetProPayPaymentStatusResponseBody()
        {
        }
        
        public GetProPayPaymentStatusResponseBody(string GetProPayPaymentStatusResult)
        {
            this.GetProPayPaymentStatusResult = GetProPayPaymentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPaymentForMerrittInsuranceTest", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentForMerrittInsuranceTestRequestBody Body;
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestRequest()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestRequest(AuthorizeProPayPaymentForMerrittInsuranceTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CCNumber;
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestRequestBody()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestRequestBody(string CCNumber)
        {
            this.CCNumber = CCNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProPayPaymentForMerrittInsuranceTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthorizeProPayPaymentForMerrittInsuranceTestResponseBody Body;
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestResponse()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestResponse(AuthorizeProPayPaymentForMerrittInsuranceTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeProPayPaymentForMerrittInsuranceTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long TransactionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AVSResponseCode;
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestResponseBody()
        {
        }
        
        public AuthorizeProPayPaymentForMerrittInsuranceTestResponseBody(string AuthCode, long TransactionNumber, int TransactionStatus, string AVSResponseCode)
        {
            this.AuthCode = AuthCode;
            this.TransactionNumber = TransactionNumber;
            this.TransactionStatus = TransactionStatus;
            this.AVSResponseCode = AVSResponseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthAndSaveCardSpecifyingCCPaymentID
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthAndSaveCardSpecifyingCCPaymentID", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthAndSaveCardSpecifyingCCPaymentIDBody Body;
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID()
        {
        }
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID(GetPreAuthAndSaveCardSpecifyingCCPaymentIDBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthAndSaveCardSpecifyingCCPaymentIDBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCardHolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sBillingStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sBillingPostalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal DollarAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long ContactID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int iExpMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int iExpYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Guid creditCardPaymentID;
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentIDBody()
        {
        }
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentIDBody(string sAccCode, string sClientApp, string sOrderID, string sUserID, string sCardHolderName, string sBillingStreet, string sBillingPostalCode, decimal DollarAmount, long ContactID, string sCardNumber, int iExpMonth, int iExpYear, System.Guid creditCardPaymentID)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sOrderID = sOrderID;
            this.sUserID = sUserID;
            this.sCardHolderName = sCardHolderName;
            this.sBillingStreet = sBillingStreet;
            this.sBillingPostalCode = sBillingPostalCode;
            this.DollarAmount = DollarAmount;
            this.ContactID = ContactID;
            this.sCardNumber = sCardNumber;
            this.iExpMonth = iExpMonth;
            this.iExpYear = iExpYear;
            this.creditCardPaymentID = creditCardPaymentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthAndSaveCardSpecifyingCCPaymentID1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthAndSaveCardSpecifyingCCPaymentIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID1Body Body;
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID1()
        {
        }
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID1(GetPreAuthAndSaveCardSpecifyingCCPaymentID1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthAndSaveCardSpecifyingCCPaymentID1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sAuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sAVSResponseCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Guid ccToken;
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID1Body()
        {
        }
        
        public GetPreAuthAndSaveCardSpecifyingCCPaymentID1Body(string sApproval, string sPaymentID, string sAuthCode, string sAVSResponseCode, string sMessage, System.Guid ccToken)
        {
            this.sApproval = sApproval;
            this.sPaymentID = sPaymentID;
            this.sAuthCode = sAuthCode;
            this.sAVSResponseCode = sAVSResponseCode;
            this.sMessage = sMessage;
            this.ccToken = ccToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthAndSaveCard
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthAndSaveCard", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthAndSaveCardBody Body;
        
        public GetPreAuthAndSaveCard()
        {
        }
        
        public GetPreAuthAndSaveCard(GetPreAuthAndSaveCardBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthAndSaveCardBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCardHolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sBillingStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sBillingPostalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal DollarAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long ContactID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int iExpMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int iExpYear;
        
        public GetPreAuthAndSaveCardBody()
        {
        }
        
        public GetPreAuthAndSaveCardBody(string sAccCode, string sClientApp, string sOrderID, string sUserID, string sCardHolderName, string sBillingStreet, string sBillingPostalCode, decimal DollarAmount, long ContactID, string sCardNumber, int iExpMonth, int iExpYear)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sOrderID = sOrderID;
            this.sUserID = sUserID;
            this.sCardHolderName = sCardHolderName;
            this.sBillingStreet = sBillingStreet;
            this.sBillingPostalCode = sBillingPostalCode;
            this.DollarAmount = DollarAmount;
            this.ContactID = ContactID;
            this.sCardNumber = sCardNumber;
            this.iExpMonth = iExpMonth;
            this.iExpYear = iExpYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthAndSaveCard1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthAndSaveCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthAndSaveCard1Body Body;
        
        public GetPreAuthAndSaveCard1()
        {
        }
        
        public GetPreAuthAndSaveCard1(GetPreAuthAndSaveCard1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthAndSaveCard1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sAuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sAVSResponseCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Guid ccToken;
        
        public GetPreAuthAndSaveCard1Body()
        {
        }
        
        public GetPreAuthAndSaveCard1Body(string sApproval, string sPaymentID, string sAuthCode, string sAVSResponseCode, string sMessage, System.Guid ccToken)
        {
            this.sApproval = sApproval;
            this.sPaymentID = sPaymentID;
            this.sAuthCode = sAuthCode;
            this.sAVSResponseCode = sAVSResponseCode;
            this.sMessage = sMessage;
            this.ccToken = ccToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthUsingToken
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthUsingToken", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthUsingTokenBody Body;
        
        public GetPreAuthUsingToken()
        {
        }
        
        public GetPreAuthUsingToken(GetPreAuthUsingTokenBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthUsingTokenBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCardHolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sBillingStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sBillingPostalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal DollarAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Guid ccToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int iExpMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int iExpYear;
        
        public GetPreAuthUsingTokenBody()
        {
        }
        
        public GetPreAuthUsingTokenBody(string sAccCode, string sClientApp, string sOrderID, string sUserID, string sCardHolderName, string sBillingStreet, string sBillingPostalCode, decimal DollarAmount, System.Guid ccToken, int iExpMonth, int iExpYear)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sOrderID = sOrderID;
            this.sUserID = sUserID;
            this.sCardHolderName = sCardHolderName;
            this.sBillingStreet = sBillingStreet;
            this.sBillingPostalCode = sBillingPostalCode;
            this.DollarAmount = DollarAmount;
            this.ccToken = ccToken;
            this.iExpMonth = iExpMonth;
            this.iExpYear = iExpYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthUsingToken1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthUsingTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthUsingToken1Body Body;
        
        public GetPreAuthUsingToken1()
        {
        }
        
        public GetPreAuthUsingToken1(GetPreAuthUsingToken1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthUsingToken1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sAuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sAVSResponseCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sMessage;
        
        public GetPreAuthUsingToken1Body()
        {
        }
        
        public GetPreAuthUsingToken1Body(string sApproval, string sPaymentID, string sAuthCode, string sAVSResponseCode, string sMessage)
        {
            this.sApproval = sApproval;
            this.sPaymentID = sPaymentID;
            this.sAuthCode = sAuthCode;
            this.sAVSResponseCode = sAVSResponseCode;
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuth", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthRequestBody Body;
        
        public GetPreAuthRequest()
        {
        }
        
        public GetPreAuthRequest(GetPreAuthRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCardHolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sBillingStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sBillingPostalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal DollarAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int iExpMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int iExpYear;
        
        public GetPreAuthRequestBody()
        {
        }
        
        public GetPreAuthRequestBody(string sAccCode, string sClientApp, string sOrderID, string sUserID, string sCardHolderName, string sBillingStreet, string sBillingPostalCode, decimal DollarAmount, string sCardNumber, int iExpMonth, int iExpYear)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sOrderID = sOrderID;
            this.sUserID = sUserID;
            this.sCardHolderName = sCardHolderName;
            this.sBillingStreet = sBillingStreet;
            this.sBillingPostalCode = sBillingPostalCode;
            this.DollarAmount = DollarAmount;
            this.sCardNumber = sCardNumber;
            this.iExpMonth = iExpMonth;
            this.iExpYear = iExpYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPreAuthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPreAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetPreAuthResponseBody Body;
        
        public GetPreAuthResponse()
        {
        }
        
        public GetPreAuthResponse(GetPreAuthResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPreAuthResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sAuthCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sAVSResponseCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sMessage;
        
        public GetPreAuthResponseBody()
        {
        }
        
        public GetPreAuthResponseBody(string sApproval, string sPaymentID, string sAuthCode, string sAVSResponseCode, string sMessage)
        {
            this.sApproval = sApproval;
            this.sPaymentID = sPaymentID;
            this.sAuthCode = sAuthCode;
            this.sAVSResponseCode = sAVSResponseCode;
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoPostAuthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoPostAuth", Namespace="http://tempuri.org/", Order=0)]
        public DoPostAuthRequestBody Body;
        
        public DoPostAuthRequest()
        {
        }
        
        public DoPostAuthRequest(DoPostAuthRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoPostAuthRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal DollarAmount;
        
        public DoPostAuthRequestBody()
        {
        }
        
        public DoPostAuthRequestBody(string sAccCode, string sClientApp, string sPaymentID, string sUserID, decimal DollarAmount)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sPaymentID = sPaymentID;
            this.sUserID = sUserID;
            this.DollarAmount = DollarAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoPostAuthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoPostAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public DoPostAuthResponseBody Body;
        
        public DoPostAuthResponse()
        {
        }
        
        public DoPostAuthResponse(DoPostAuthResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoPostAuthResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMessage;
        
        public DoPostAuthResponseBody()
        {
        }
        
        public DoPostAuthResponseBody(string sApproval, string sMessage)
        {
            this.sApproval = sApproval;
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueVoidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueVoid", Namespace="http://tempuri.org/", Order=0)]
        public IssueVoidRequestBody Body;
        
        public IssueVoidRequest()
        {
        }
        
        public IssueVoidRequest(IssueVoidRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IssueVoidRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        public IssueVoidRequestBody()
        {
        }
        
        public IssueVoidRequestBody(string sAccCode, string sClientApp, string sPaymentID, string sUserID)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sPaymentID = sPaymentID;
            this.sUserID = sUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueVoidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueVoidResponse", Namespace="http://tempuri.org/", Order=0)]
        public IssueVoidResponseBody Body;
        
        public IssueVoidResponse()
        {
        }
        
        public IssueVoidResponse(IssueVoidResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IssueVoidResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMessage;
        
        public IssueVoidResponseBody()
        {
        }
        
        public IssueVoidResponseBody(string sApproval, string sMessage)
        {
            this.sApproval = sApproval;
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueCredit", Namespace="http://tempuri.org/", Order=0)]
        public IssueCreditRequestBody Body;
        
        public IssueCreditRequest()
        {
        }
        
        public IssueCreditRequest(IssueCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IssueCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPaymentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal DollarAmount;
        
        public IssueCreditRequestBody()
        {
        }
        
        public IssueCreditRequestBody(string sAccCode, string sClientApp, string sPaymentID, string sUserID, decimal DollarAmount)
        {
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sPaymentID = sPaymentID;
            this.sUserID = sUserID;
            this.DollarAmount = DollarAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public IssueCreditResponseBody Body;
        
        public IssueCreditResponse()
        {
        }
        
        public IssueCreditResponse(IssueCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IssueCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMessage;
        
        public IssueCreditResponseBody()
        {
        }
        
        public IssueCreditResponseBody(string sApproval, string sMessage)
        {
            this.sApproval = sApproval;
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SettleTransactionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SettleTransactions", Namespace="http://tempuri.org/", Order=0)]
        public SettleTransactionsRequestBody Body;
        
        public SettleTransactionsRequest()
        {
        }
        
        public SettleTransactionsRequest(SettleTransactionsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SettleTransactionsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sSettleMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sAccCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sClientApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sUserID;
        
        public SettleTransactionsRequestBody()
        {
        }
        
        public SettleTransactionsRequestBody(string sSettleMode, string sAccCode, string sClientApp, string sUserID)
        {
            this.sSettleMode = sSettleMode;
            this.sAccCode = sAccCode;
            this.sClientApp = sClientApp;
            this.sUserID = sUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SettleTransactionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SettleTransactionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SettleTransactionsResponseBody Body;
        
        public SettleTransactionsResponse()
        {
        }
        
        public SettleTransactionsResponse(SettleTransactionsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SettleTransactionsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sApproval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMessage;
        
        public SettleTransactionsResponseBody()
        {
        }
        
        public SettleTransactionsResponseBody(string sApproval, string sMessage)
        {
            this.sApproval = sApproval;
            this.sMessage = sMessage;
        }
    }
}
